import { z } from 'zod';

/**
 * Base user schema - represents a complete user object
 */
export const userSchema = z.object({
  id: z.number().int().positive(),
  name: z.string().min(1, 'Name is required').max(100),
  email: z.string().email('Invalid email format'),
});

/**
 * Create user schema - omits id (auto-generated by server)
 */
export const createUserSchema = userSchema.omit({ id: true });

/**
 * Update user schema - all fields optional (partial update)
 */
export const updateUserSchema = userSchema.omit({ id: true }).partial();

/**
 * User ID parameter schema - validates route parameters
 */
export const userIdParamSchema = z.object({
  id: z.string().regex(/^\d+$/, 'ID must be numeric'),
});

/**
 * TypeScript types inferred from schemas
 * These ensure type safety across the application
 */
export type User = z.infer<typeof userSchema>;
export type CreateUserDto = z.infer<typeof createUserSchema>;
export type UpdateUserDto = z.infer<typeof updateUserSchema>;
export type UserIdParam = z.infer<typeof userIdParamSchema>;
